### ISSUE TITLE
Desarrollar reporte de base para control de impuestos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-accounting#7]

**Comment by Sir-R2D2** [comment]
Controlador
    TaxControlManager.php

Repositorio: 
    Repositories/JournalVoucher/EloquentTaxControlGridRepository.php

Servicio:
    JournalManager.php

Vista: 
    tax-control.blade.php

Prefijos: 
    acct-tc-, acctTc, acct_tc
